### ISSUE TITLE
First point result doesn't have the correct format

### ISSUE THREAD

**Issue by antoinealb** [cvra/molly-the-motion-planner#12]
When running get_path, the first point returned is a 3-tuple instead of the 4-tuple described in the readme.

**Comment by antoinealb** [comment]
correction: it also appears for other points in the trajectory.

**Comment by 31415us** [comment]
i'll look into it, thanks for reporting

Sent from my iPhone

On 26.04.2015, at 18:46, "Antoine Albertelli" <notifications@github.com<mailto:notifications@github.com>> wrote:


correction: it also appears for other points in the trajectory.
